name: "Semgrep"

on:
  push:
    branches: ["insecure-tr03161-eval"]
  pull_request:
    branches: ["insecure-tr03161-eval"]

permissions:
  contents: read
  security-events: write

jobs:
  analyze:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Set up Python 3.12
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
        with:
          python-version: "3.12"

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip==25.3
          pip install semgrep==1.145.0

      - name: Run Semgrep Analysis
        run: |
          semgrep \
            --config p/flask \
            --config p/python \
            --config p/owasp-top-ten \
            --config p/cwe-top-25 \
            --sarif-output semgrep.sarif \
            --verbose \
            src/

        continue-on-error: true

      - name: Upload SARIF Results
        uses: github/codeql-action/upload-sarif@c43362b91a940600cde2ebae39ec7a35ad66bdc0
        with:
          sarif_file: semgrep.sarif